import { 
  Shirt, 
  Footprints, 
  Watch, 
  Smartphone, 
  Tv, 
  Zap, 
  Sparkles, 
  HeartPulse, 
  Baby, 
  Gamepad2, 
  Dumbbell, 
  Monitor, 
  Briefcase, 
  Laptop, 
  Car, 
  Dog, 
  Stethoscope, 
  Palette, 
  PartyPopper, 
  UtensilsCrossed, 
  BookOpen, 
  Lamp, 
  Armchair, 
  LayoutGrid,
  ShoppingCart,
  Sprout
} from "lucide-react";

export const categories = [
  { label: "All", value: "all", icon: LayoutGrid },
  { label: "Clothing & Apparel", value: "clothing-apparel", icon: Shirt },
  { label: "Footwear", value: "footwear", icon: Footprints },
  { label: "Fashion Accessories", value: "fashion-accessories", icon: Watch },
  { label: "Electronics", value: "electronics", icon: Tv },
  { label: "Phone Accessories", value: "phone-accessories", icon: Smartphone },
  { label: "Home Appliances", value: "home-appliances", icon: Zap },
  { label: "Beauty Products", value: "beauty-products", icon: Sparkles },
  { label: "Personal Care Items", value: "personal-care", icon: HeartPulse },
  { label: "Watches & Jewelry", value: "watches-jewelry", icon: Watch },
  { label: "Groceries & Packaged Foods", value: "groceries-packaged-foods", icon: ShoppingCart },
  { label: "Furniture", value: "furniture", icon: Armchair },
  { label: "Home Décor", value: "home-decor", icon: Lamp },
  { label: "Kitchenware", value: "kitchenware", icon: UtensilsCrossed },
  { label: "Books & Stationery", value: "books-stationery", icon: BookOpen },
  { label: "Baby Products", value: "baby-products", icon: Baby },
  { label: "Toys & Games", value: "toys-games", icon: Gamepad2 },
  { label: "Sports & Fitness Equipment", value: "sports-fitness", icon: Dumbbell },
  { label: "Computer Accessories", value: "computer-accessories", icon: Monitor },
  { label: "Office Supplies", value: "office-supplies", icon: Briefcase },
  { label: "Digital Products", value: "digital-products", icon: Laptop },
  { label: "Automotive Accessories", value: "automotive-accessories", icon: Car },
  { label: "Pet Supplies", value: "pet-supplies", icon: Dog },
  { label: "Health Products", value: "health-products", icon: Stethoscope },
  { label: "Craft & DIY Supplies", value: "craft-diy", icon: Palette },
  { label: "Event & Party Supplies", value: "event-party-supplies", icon: PartyPopper },
  { label: "Farm Products", value: "farm-products", icon: Sprout },
];
